name: Run Typesense DocSearch Scraper
description: Crawl and index your documentation site for Typesense DocSearch

branding:
  icon: search
  color: black

inputs:
    api-key:
        description: Your Typesense API Key.
        required: true
    host:
        description: The hostname or IP address of your Typesense server.
        required: true
    port:
        description: The port of your Typesense server. Defaults to "8108".
        required: false
        default: "8108"
    protocol:
        description: The protocol over which the scraper should connect to your Typesense server. Defaults to "http".
        required: false
        default: http
    config:
        description: The path to your DocSearch config JSON file, relative to the root of your repository. Defaults to "docsearch.config.json".
        required: false
        default: docsearch.config.json

runs:
  using: docker
  image: docker://typesense/docsearch-scraper
  env:
      TYPESENSE_API_KEY: ${{ inputs.api-key }}
      TYPESENSE_HOST: ${{ inputs.host }}
      TYPESENSE_PORT: ${{ inputs.port }}
      TYPESENSE_PROTOCOL: ${{ inputs.protocol }}
      CONFIG: ${{ inputs.config }}
